name: openidconnect_platform_interface
description: Platform interface for OpenIdConnect.
version: 1.0.17
homepage: https://github.com/4D-Technologies/openidconnect_flutter/tree/main/openidconnect_platform_interface

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  flutter_test:
    sdk: flutter
